[package]
name = "rusty-trails"
version = "0.1.0"
authors = ["Christopher Schmidt <christopher.schmidt@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rawloader = "0.36.2"
rayon = "1.3.0"
